version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "3803:80"
    volumes:
      - ./web:/app
      - balas-result-files:/balas-result-files
    depends_on:
      - db
    environment:
      - BALAS_DB_NAME=db
    restart: on-failure
  ala-scan:
    build:
      context: .
      dockerfile: ./ala-scan/Dockerfile
    depends_on:
      - db
    environment:
      - BALAS_DB_NAME=db
      - OMP_NUM_THREADS=1
      - PYTHONPATH=/app/alaScanApp-dist/alaScanApp
      - PYTHONUNBUFFERED=0
      - SCAN_PROCS=2
      - AUTO_PROCS=3
      - MANUAL_PROCS=3
      - RESIDUES_PROCS=3
    restart: on-failure
    volumes:
      - balas-result-files:/balas-result-files
  db:
    image: mongo

volumes:
    balas-result-files:
