version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "3803:80"
    volumes:
      - ./web:/app
      - result-files:/result-files
    depends_on:
      - db
    restart: on-failure
  ala-scan:
    build:
      context: .
      dockerfile: ./ala-scan/Dockerfile
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=0
      - SCAN_PROCS=2
      - PYTHONPATH=/app/alaScanApp-dist/alaScanApp
    restart: on-failure
    volumes:
      - result-files:/result-files
  db:
    image: mongo

volumes:
    result-files:
