getSD: calculateSD.cpp help.cpp main.cpp operators.cpp printAvgContent.cpp processLine.cpp readFile.cpp
	$(CXX) -O2 -g0 -Wall -fmessage-length=0 calculateSD.cpp help.cpp main.cpp operators.cpp printAvgContent.cpp processLine.cpp readFile.cpp -o getSD
clean:
	rm -f getSD
